# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1db696abebaff237fe79cd4a45b452a8"
name = "BSS TRAINING APP"
handle = "bss-training-app-1"
application_url = "https://represents-cams-facility-guardian.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "bss-train-app.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://represents-cams-facility-guardian.trycloudflare.com/auth/callback",
  "https://represents-cams-facility-guardian.trycloudflare.com/auth/shopify/callback",
  "https://represents-cams-facility-guardian.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
